replicaCount: 1
image:
  repository: "ghcr.io/laskavchuk/kbot/helm-kbot"
  tag: "v1.0.3-e6d2bea"
  arch: "amd64"
  pullPolicy: "IfNotPresent"

imagePullSecrets:
  - name: ghcr-secret   # секрет для GHCR

secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"

securityContext:
  privileged: true
