replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "laskavchuk/kbot/helm-kbot"
  tag: "v1.0.3-0f12234"
  os: linux
  arch: amd64
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
