replicaCount: 1
image:
  repository: "ghcr.io/laskavchuk/kbot"
  tag: "v1.0.3-b385604"
  arch: "amd64"
  pullPolicy: "IfNotPresent"
imagePullSecrets:
  - name: ghcr-secret # секрет для GHCR
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
