replicaCount: 1
image:
  repository: "ghcr.io/laskavchuk/kbot"
  tag: "v1.0.3-314b41c"
  arch: "amd64"
  os: "linux"
  pullPolicy: "IfNotPresent"
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
