replicaCount: 1
image:
  repository: "ghcr.io/laskavchuk/kbot"
  tag: "v1.0.3-74d0841"
  arch: "amd64"
  os: "linux"
  pullPolicy: "IfNotPresent"
imagePullSecrets:
  - name: ghcr-secret
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
